const RESET_BOARD ='RESET_BOARD';
const OPEN_CELL = 'OPEN_CELL';
const TOGGLE_CELL_FLAG = 'TOGGLE_CELL_FLAG';
const UNFLAG_CELL = 'UNFLAG_CELL';


export {RESET_BOARD, OPEN_CELL,TOGGLE_CELL_FLAG,UNFLAG_CELL};